apiVersion: v2
name: furiosa-npu-operator
description: A Helm chart for `furiosa-npu-operator`
type: application

version: 2025.4.0-rc0
appVersion: 2025.4.0-rc0

dependencies:
  - name: node-feature-discovery
    version: "0.17.2"
    condition: node-feature-discovery.enabled
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
