apiVersion: v2
name: furiosa-feature-discovery
description: A Helm chart for furiosa-feature-discovery
type: application
version: 2026.1.0-rc0
appVersion: 2026.1.0-rc0

dependencies:
  - name: node-feature-discovery
    version: "0.17.2"
    condition: node-feature-discovery.enabled
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
