apiVersion: v2
name: furiosa-feature-discovery
description: A Helm chart for furiosa-feature-discovery
type: application
version: 0.1.0

dependencies:
  - name: node-feature-discovery
    version: "0.15.3"
    condition: node-feature-discovery.enabled
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
