apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceclaimtemplates"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceclaimtemplates/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceslices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceslices/status"]
    verbs: ["update", "patch"]
