apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "furiosa-dra-driver.fullname" . }}-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "furiosa-dra-driver.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default "kube-system" }}
roleRef:
  kind: ClusterRole
  name: {{ include "furiosa-dra-driver.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
