apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: {{ .Values.deviceClass.name | default "npu.furiosa.ai" }}
spec:
  selectors:
    - cel:
        expression: "device.driver == 'npu.furiosa.ai'"
