apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "furiosa-dra-driver.fullname" . }}-role-binding
  namespace: {{ .Values.namespace | default "kube-system" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "furiosa-dra-driver.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default "kube-system" }}
roleRef:
  kind: Role
  name: {{ include "furiosa-dra-driver.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
