{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "furiosa-dra-driver.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "kube-system" }}
  labels:
    {{- include "furiosa-dra-driver.labels" . | nindent 4 }}
{{- end }}
