apiVersion: v2
name: llm-d-modelservice
description: A Helm chart for ModelService in llm-d
type: application
version: "v0.3.16-furiosa"
appVersion: "v0.3.0"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: "2.27.0"
